version: '3.6'

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    restart: unless-stopped
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${CONF_PATH}:/config
      - ${DATA_PATH}/backups:/backups
    ports:
      - ${PORT}:8200